### ISSUE TITLE
attribute error 'str' object has no attribute 'name'

### ISSUE THREAD

**Issue by Kxpark** [akcorut/kGWASflow#2] opened 2023-01-26 19:33 UTC
Howdy,
I thought I got all of the input files ready and configured correctly however I cannot seem to fix this error in the code.
Hopefully you can help!

line 1222, in __eq__
    return self.name == other.name and self.output == other.output
AttributeError: 'str' object has no attribute 'name'

![image](https://user-images.githubusercontent.com/104218928/214931882-e9124b8f-9a99-4f9a-bae9-c046119069a5.png)
![image](https://user-images.githubusercontent.com/104218928/214932126-789a4bac-d8ad-477c-ac75-1a9987d27a25.png)

**Comment by akcorut** [comment] 2023-01-26 21:56
Hey @Kxpark,

Thanks for reporting this. The problem seems to be caused by the version of snakemake (previously reported here: https://github.com/snakemake/snakemake/issues/1899). I update the version of snakemake and changed the environment.yaml file with the commit fdb9255958411b821b5db765577e715def0dcb87. This should fix the issue.

Let me know if the problem continues.

Thanks,
Kivanc

**Comment by Kxpark** [comment] 2023-01-26 22:20
It seemed to resolve the problem and allow me to run a dry run. Thank you for resolving the issue so quickly!

**Comment by akcorut** [comment] 2023-01-26 22:33
No problem. I'm glad the issue got fixed. I'm closing this issue now but feel free to open a new one if you have any issues with the pipeline in the future.

Thanks,
Kivanc

**Closed by akcorut** 2023-01-26 22:33 UTC
